# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b780597ad4c1e6d4642217177378d2dfb02c83b5da6be1d3dcb799ed22f44758838a2cd696828ead976dc7d466631260571ee3ea2d643ed8b38e7abb176af2d

test:
  secret_key_base: b7ead7ef50825602219dd4214d301c9b7bd14e42a9efcf649b8eeafd728ab0f24265cac942deccdd97f74bf76db6e325bf9c7806f1f6b328943acae8a6fb8167

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
